-- PHASE 1: CREATE WAREHOUSE

CREATE WAREHOUSE IF NOT EXISTS RETAIL_DW_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE RETAIL_DW_WH;


-- PHASE 2: CREATE DATABASE AND SCHEMA

CREATE DATABASE IF NOT EXISTS RETAIL_DW_DB;

USE DATABASE RETAIL_DW_DB;

CREATE SCHEMA IF NOT EXISTS SALES_SCHEMA;

USE SCHEMA SALES_SCHEMA;


-- PHASE 3: CREATE FILE FORMAT AND STAGE

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE RETAIL_DW_STAGE
FILE_FORMAT = CSV_FORMAT;

SHOW STAGES;

LIST @RETAIL_DW_STAGE;


-- PHASE 4: CREATE DIMENSION TABLES

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE NUMBER(12,2)
);

CREATE OR REPLACE TABLE DIM_BRANCH (
    BRANCH_ID INT PRIMARY KEY,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50),
    MANAGER_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID INT PRIMARY KEY,
    DATE DATE,
    DAY INT,
    DAY_NAME VARCHAR(20),
    WEEK_NO INT,
    MONTH VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR INT,
    IS_WEEKEND VARCHAR(10)
);


-- PHASE 5: CREATE FACT TABLE

CREATE OR REPLACE TABLE FACT_SALES (
    SALE_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    BRANCH_ID INT,
    DATE_ID INT,
    QUANTITY INT,
    TOTAL_AMOUNT NUMBER(12,2),

    CONSTRAINT FK_SALES_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_SALES_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_SALES_BRANCH
        FOREIGN KEY (BRANCH_ID)
        REFERENCES DIM_BRANCH(BRANCH_ID),

    CONSTRAINT FK_SALES_DATE
        FOREIGN KEY (DATE_ID)
        REFERENCES DIM_DATE(DATE_ID)
);


-- PHASE 6: LOAD CUSTOMER DATA

COPY INTO DIM_CUSTOMER
FROM @RETAIL_DW_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT')
ON_ERROR = 'CONTINUE';


-- PHASE 7: LOAD PRODUCT DATA

COPY INTO DIM_PRODUCT
FROM @RETAIL_DW_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT')
ON_ERROR = 'CONTINUE';


-- PHASE 8: LOAD BRANCH DATA

COPY INTO DIM_BRANCH
(
    BRANCH_ID,
    BRANCH_NAME,
    CITY,
    STATE,
    REGION,
    MANAGER_NAME
)
FROM (
    SELECT
        $1::INT,
        $2::VARCHAR,
        $3::VARCHAR,
        $4::VARCHAR,
        $5::VARCHAR,
        $6::VARCHAR
    FROM @RETAIL_DW_STAGE/branches.csv
)
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT')
ON_ERROR = 'CONTINUE';


-- PHASE 9: LOAD DATE DATA

COPY INTO DIM_DATE
(
    DATE_ID,
    DATE,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH,
    QUARTER,
    YEAR,
    IS_WEEKEND
)
FROM (
    SELECT
        $1::INT,
        $2::DATE,
        $3::INT,
        $4::VARCHAR,
        $5::INT,
        $6::VARCHAR,
        $7::VARCHAR,
        $8::INT,
        $9::VARCHAR
    FROM @RETAIL_DW_STAGE/calendar.csv
)
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT')
ON_ERROR = 'CONTINUE';


-- PHASE 10: LOAD SALES DATA

COPY INTO FACT_SALES
(
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
)
FROM (
    SELECT
        $1::INT,
        $2::INT,
        $3::INT,
        $4::INT,
        $5::INT,
        $6::INT,
        $7::NUMBER(12,2)
    FROM @RETAIL_DW_STAGE/sales.csv
)
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT')
ON_ERROR = 'CONTINUE';


-- PHASE 11: VERIFY TABLES

SHOW TABLES;

SELECT * FROM DIM_CUSTOMER ORDER BY CUSTOMER_ID;

SELECT * FROM DIM_PRODUCT ORDER BY PRODUCT_ID;

SELECT * FROM DIM_BRANCH ORDER BY BRANCH_ID;

SELECT * FROM DIM_DATE ORDER BY DATE_ID;

SELECT * FROM FACT_SALES ORDER BY SALE_ID;


-- PHASE 12: CHECK ROW COUNTS

SELECT 'DIM_CUSTOMER' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM DIM_CUSTOMER

UNION ALL

SELECT 'DIM_PRODUCT', COUNT(*)
FROM DIM_PRODUCT

UNION ALL

SELECT 'DIM_BRANCH', COUNT(*)
FROM DIM_BRANCH

UNION ALL

SELECT 'DIM_DATE', COUNT(*)
FROM DIM_DATE

UNION ALL

SELECT 'FACT_SALES', COUNT(*)
FROM FACT_SALES;


-- PHASE 13: CHECK DUPLICATE KEYS

SELECT CUSTOMER_ID, COUNT(*)
FROM DIM_CUSTOMER
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1;

SELECT PRODUCT_ID, COUNT(*)
FROM DIM_PRODUCT
GROUP BY PRODUCT_ID
HAVING COUNT(*) > 1;

SELECT BRANCH_ID, COUNT(*)
FROM DIM_BRANCH
GROUP BY BRANCH_ID
HAVING COUNT(*) > 1;

SELECT DATE_ID, COUNT(*)
FROM DIM_DATE
GROUP BY DATE_ID
HAVING COUNT(*) > 1;

SELECT SALE_ID, COUNT(*)
FROM FACT_SALES
GROUP BY SALE_ID
HAVING COUNT(*) > 1;


-- PHASE 14: CHECK FOREIGN KEYS

SELECT f.*
FROM FACT_SALES f
LEFT JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
WHERE c.CUSTOMER_ID IS NULL;

SELECT f.*
FROM FACT_SALES f
LEFT JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
WHERE p.PRODUCT_ID IS NULL;

SELECT f.*
FROM FACT_SALES f
LEFT JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
WHERE b.BRANCH_ID IS NULL;

SELECT f.*
FROM FACT_SALES f
LEFT JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
WHERE d.DATE_ID IS NULL;


-- PHASE 15: CUSTOMER-WISE SALES

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;


-- PHASE 16: PRODUCT-WISE REVENUE

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY
ORDER BY TOTAL_REVENUE DESC;


-- PHASE 17: BRANCH-WISE REVENUE

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC;


-- PHASE 18: STATE-WISE REVENUE

SELECT
    b.STATE,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.STATE
ORDER BY TOTAL_REVENUE DESC;


-- PHASE 19: MONTHLY REVENUE

SELECT
    d.YEAR,
    d.MONTH,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY
    d.YEAR,
    d.MONTH
ORDER BY
    d.YEAR,
    MIN(d.DATE_ID);


-- PHASE 20: QUARTERLY REVENUE

SELECT
    d.YEAR,
    d.QUARTER,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY
    d.YEAR,
    d.QUARTER
ORDER BY
    d.YEAR,
    d.QUARTER;


-- PHASE 21: TOP 10 CUSTOMERS

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;


-- PHASE 22: TOP 10 PRODUCTS

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;


-- PHASE 23: TOP 10 BRANCHES

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;


-- PHASE 24: CATEGORY-WISE REVENUE

SELECT
    p.CATEGORY,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.CATEGORY
ORDER BY TOTAL_REVENUE DESC;


-- PHASE 25: CUSTOMER PURCHASE TREND

SELECT
    c.CUSTOMER_NAME,
    d.DATE,
    SUM(f.QUANTITY) AS QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES f
JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY
    c.CUSTOMER_NAME,
    d.DATE
ORDER BY
    c.CUSTOMER_NAME,
    d.DATE;


-- PHASE 26: PRODUCT PERFORMANCE

SELECT
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.BRAND,
    SUM(f.QUANTITY) AS UNITS_SOLD,
    SUM(f.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.BRAND
ORDER BY REVENUE DESC;


-- PHASE 27: BRANCH PERFORMANCE

SELECT
    b.BRANCH_NAME,
    b.CITY,
    b.STATE,
    b.REGION,
    SUM(f.QUANTITY) AS UNITS_SOLD,
    SUM(f.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY
    b.BRANCH_NAME,
    b.CITY,
    b.STATE,
    b.REGION
ORDER BY REVENUE DESC;


-- PHASE 28: REGIONAL SALES

SELECT
    b.REGION,
    SUM(f.QUANTITY) AS TOTAL_QUANTITY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.REGION
ORDER BY TOTAL_REVENUE DESC;


-- PHASE 29: SALES TREND

SELECT
    d.DATE,
    SUM(f.QUANTITY) AS QUANTITY_SOLD,
    SUM(f.TOTAL_AMOUNT) AS REVENUE
FROM FACT_SALES f
JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY d.DATE
ORDER BY d.DATE;


-- PHASE 30: COMPLETE STAR SCHEMA VIEW

CREATE OR REPLACE VIEW VW_RETAIL_SALES AS
SELECT
    f.SALE_ID,

    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CITY AS CUSTOMER_CITY,
    c.STATE AS CUSTOMER_STATE,
    c.MEMBERSHIP,

    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.BRAND,
    p.PRICE,

    b.BRANCH_ID,
    b.BRANCH_NAME,
    b.CITY AS BRANCH_CITY,
    b.STATE AS BRANCH_STATE,
    b.REGION,
    b.MANAGER_NAME,

    d.DATE_ID,
    d.DATE,
    d.DAY,
    d.DAY_NAME,
    d.WEEK_NO,
    d.MONTH,
    d.QUARTER,
    d.YEAR,
    d.IS_WEEKEND,

    f.QUANTITY,
    f.TOTAL_AMOUNT

FROM FACT_SALES f

JOIN DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID

JOIN DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID

JOIN DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID

JOIN DIM_DATE d
    ON f.DATE_ID = d.DATE_ID;


-- PHASE 31: TEST STAR SCHEMA VIEW

SELECT *
FROM VW_RETAIL_SALES
ORDER BY SALE_ID;