CREATE WAREHOUSE RETAIL_DW_WH WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE RETAIL_DW_WH;

CREATE DATABASE RETAIL_DW_DB;
USE DATABASE RETAIL_DW_DB;

CREATE SCHEMA SALES_SCHEMA;
USE SCHEMA SALES_SCHEMA;

SELECT
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE NUMBER(12,2)
);

CREATE OR REPLACE TABLE DIM_BRANCH (
    BRANCH_ID INT PRIMARY KEY,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID INT PRIMARY KEY,
    DATE DATE,
    MONTH VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR INT
);

SHOW TABLES;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE RETAIL_DW_STAGE
FILE_FORMAT = CSV_FORMAT;

SHOW STAGES;

LIST @RETAIL_DW_STAGE;

COPY INTO DIM_CUSTOMER
FROM @RETAIL_DW_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO DIM_PRODUCT
FROM @RETAIL_DW_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO DIM_BRANCH
(
    BRANCH_ID,
    BRANCH_NAME,
    CITY,
    STATE
)
FROM (
    SELECT
        $1::INT,
        $2::VARCHAR,
        $3::VARCHAR,
        $4::VARCHAR
    FROM @RETAIL_DW_STAGE/branches.csv
)
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO DIM_DATE
(
    DATE_ID,
    DATE,
    MONTH,
    QUARTER,
    YEAR
)
FROM (
    SELECT
        $1,
        $2,
        $6,
        $7,
        $8
    FROM @RETAIL_DW_STAGE/calendar.csv
)
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

SELECT COUNT(*) AS CUSTOMER_COUNT
FROM DIM_CUSTOMER;

SELECT COUNT(*) AS PRODUCT_COUNT
FROM DIM_PRODUCT;

SELECT COUNT(*) AS BRANCH_COUNT
FROM DIM_BRANCH;

SELECT COUNT(*) AS DATE_COUNT
FROM DIM_DATE;

-- Fact
CREATE OR REPLACE TABLE FACT_SALES (
    SALE_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    BRANCH_ID INT,
    DATE_ID INT,
    QUANTITY INT,
    TOTAL_AMOUNT NUMBER(12,2)
);

COPY INTO FACT_SALES
FROM @RETAIL_DW_STAGE/sales.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

SELECT COUNT(*) AS TOTAL_SALES
FROM FACT_SALES;

SELECT * FROM FACT_SALES
ORDER BY SALE_ID
LIMIT 10;

-- Star Schema
SELECT f.SALE_ID, c.CUSTOMER_NAME, p.PRODUCT_NAME, b.BRANCH_NAME, d.DATE, f.QUANTITY, f.TOTAL_AMOUNT FROM FACT_SALES f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_ID = c.CUSTOMER_ID
JOIN DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
JOIN DIM_BRANCH b ON f.BRANCH_ID = b.BRANCH_ID
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
ORDER BY f.SALE_ID
LIMIT 10;


SELECT c.CUSTOMER_ID, c.CUSTOMER_NAME, SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES f
JOIN DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT b.BRANCH_ID, b.BRANCH_NAME, SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES f
JOIN DIM_BRANCH b ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.BRANCH_ID, b.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT d.YEAR, d.MONTH, SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
GROUP BY d.YEAR, d.MONTH
ORDER BY d.YEAR, MIN(d.DATE);

SELECT c.STATE, SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY c.STATE
ORDER BY TOTAL_REVENUE DESC;

SELECT p.CATEGORY, SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES f
JOIN DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

SELECT c.CUSTOMER_ID, c.CUSTOMER_NAME, SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES f
JOIN DIM_CUSTOMER c ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY, SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES f
JOIN DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT b.BRANCH_ID, b.BRANCH_NAME, b.STATE, SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES f
JOIN DIM_BRANCH b ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.BRANCH_ID, b.BRANCH_NAME, b.STATE
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;

SELECT d.DATE, SUM(f.TOTAL_AMOUNT) AS DAILY_REVENUE FROM FACT_SALES f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
GROUP BY d.DATE
ORDER BY d.DATE;

SELECT d.YEAR, d.QUARTER, SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM FACT_SALES f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
GROUP BY d.YEAR, d.QUARTER
ORDER BY d.YEAR, d.QUARTER;