USE WAREHOUSE SALES_WH;

CREATE DATABASE CUSTOMER_SALES_DB;

CREATE SCHEMA CUSTOMER_SALES_DB.SALES_SCHEMA;

USE DATABASE CUSTOMER_SALES_DB;

USE SCHEMA SALES_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

SHOW FILE FORMATS;

CREATE OR REPLACE STAGE SALES_STAGE
FILE_FORMAT = CSV_FORMAT;

SHOW STAGES;

SELECT CURRENT_WAREHOUSE(),
       CURRENT_DATABASE(),
       CURRENT_SCHEMA();


LIST @SALES_STAGE;CUSTOMER_SALES_DB.SALES_SCHEMA.SALES_STAGECUSTOMER_SALES_DB.SALES_SCHEMA.CSV_FORMAT

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID INT,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    ADDRESS STRING
);

CREATE OR REPLACE TABLE FOODITEMS (
    FOOD_ID INT,
    NAME STRING,
    PRICE NUMBER(10,2),
    CATEGORY STRING,
    AVAILABILITY STRING
);

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID INT,
    CUSTOMER_ID INT,
    FOOD_ID INT,
    QUANTITY INT,
    ORDER_DATE TIMESTAMP,
    STATUS STRING,
    TOTAL_AMOUNT NUMBER(10,2)
);

SHOW TABLES;

COPY INTO CUSTOMERS
FROM @SALES_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO FOODITEMS
FROM @SALES_STAGE/fooditems.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO ORDERS
FROM @SALES_STAGE/orders.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

SELECT * FROM CUSTOMERS;
SELECT * FROM FOODITEMS;
SELECT * FROM ORDERS;

SELECT COUNT(*) AS CUSTOMER_COUNT FROM CUSTOMERS;

SELECT COUNT(*) AS FOODITEM_COUNT FROM FOODITEMS;

SELECT COUNT(*) AS ORDER_COUNT FROM ORDERS;



SELECT
    c.CUSTOMER_ID,
    CONCAT(c.FIRST_NAME, ' ', c.LAST_NAME) AS CUSTOMER_NAME,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS c
JOIN ORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME
ORDER BY c.CUSTOMER_ID;




SELECT
    c.CUSTOMER_ID,
    CONCAT(c.FIRST_NAME, ' ', c.LAST_NAME) AS CUSTOMER_NAME,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS c
JOIN ORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 1;


SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM ORDERS;


SELECT
    f.CATEGORY,
    SUM(o.TOTAL_AMOUNT) AS REVENUE
FROM FOODITEMS f
JOIN ORDERS o
    ON f.FOOD_ID = o.FOOD_ID
GROUP BY f.CATEGORY
ORDER BY REVENUE DESC;


SELECT
    STATUS,
    SUM(TOTAL_AMOUNT) AS REVENUE
FROM ORDERS
GROUP BY STATUS
ORDER BY REVENUE DESC;


SELECT
    c.CUSTOMER_ID,
    CONCAT(c.FIRST_NAME, ' ', c.LAST_NAME) AS CUSTOMER_NAME,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS c
JOIN ORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME
ORDER BY TOTAL_SPENT DESC
LIMIT 3;



SELECT
    c.CUSTOMER_ID,
    CONCAT(c.FIRST_NAME, ' ', c.LAST_NAME) AS CUSTOMER_NAME,
    COUNT(o.ORDER_ID) AS ORDERS_PLACED
FROM CUSTOMERS c
JOIN ORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME
ORDER BY ORDERS_PLACED DESC;


SELECT *
FROM ORDERS
WHERE STATUS = 'Delivered';


SELECT
    o.ORDER_ID,
    CONCAT(c.FIRST_NAME, ' ', c.LAST_NAME) AS CUSTOMER_NAME,
    o.ORDER_DATE,
    o.STATUS,
    o.TOTAL_AMOUNT
FROM ORDERS o
JOIN CUSTOMERS c
    ON o.CUSTOMER_ID = c.CUSTOMER_ID
WHERE o.ORDER_DATE > '2026-07-12'
ORDER BY o.ORDER_DATE;


CREATE OR REPLACE VIEW CUSTOMER_SALES_REPORT AS
SELECT
    c.CUSTOMER_ID,
    CONCAT(c.FIRST_NAME, ' ', c.LAST_NAME) AS CUSTOMER_NAME,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_SPENT
FROM CUSTOMERS c
JOIN ORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME;

SELECT * FROM CUSTOMER_SALES_REPORT;



SELECT *
FROM CUSTOMER_SALES_REPORT
ORDER BY TOTAL_SPENT DESC;


    