CREATE WAREHOUSE RETAIL_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
USE WAREHOUSE RETAIL_WH;

CREATE DATABASE RETAIL_DB;
USE DATABASE RETAIL_DB;

CREATE SCHEMA SALES_SCHEMA;
USE SCHEMA SALES_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE RETAIL_STAGE
FILE_FORMAT = CSV_FORMAT;

SHOW STAGES;

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID INT,
    CUSTOMER_NAME STRING,
    CITY STRING,
    MEMBERSHIP STRING
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID INT,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE BRANCHES (
    BRANCH_ID INT,
    BRANCH_NAME STRING,
    CITY STRING
);

CREATE OR REPLACE TABLE SALES (
    SALE_ID INT,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    BRANCH_ID INT,
    QUANTITY INT,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(12,2)
);

LIST @RETAIL_STAGE;

COPY INTO CUSTOMERS
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO BRANCHES
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

SELECT * FROM CUSTOMERS;

SELECT * FROM PRODUCTS;

SELECT * FROM BRANCHES;

SELECT * FROM SALES;

-- Task 5
SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE FROM SALES;

-- Task 6
SELECT c.CUSTOMER_ID, c.CUSTOMER_NAME, SUM(s.TOTAL_AMOUNT) AS TOTAL_SPENDING FROM CUSTOMERS c
JOIN SALES s ON c.CUSTOMER_ID = s.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC;

-- Task 7
SELECT b.BRANCH_ID, b.BRANCH_NAME, SUM(s.TOTAL_AMOUNT) AS TOTAL_SALES FROM BRANCHES b
JOIN SALES s ON b.BRANCH_ID = s.BRANCH_ID
GROUP BY b.BRANCH_ID, b.BRANCH_NAME
ORDER BY TOTAL_SALES DESC;

-- Task 8
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM PRODUCTS p
JOIN SALES s ON p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

-- Task 9
SELECT p.CATEGORY, SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM PRODUCTS p
JOIN SALES s ON p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY p.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

-- Task 10
SELECT b.BRANCH_ID, b.BRANCH_NAME, SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM BRANCHES b
JOIN SALES s ON b.BRANCH_ID = s.BRANCH_ID
GROUP BY b.BRANCH_ID, b.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

-- Task 11
SELECT c.CUSTOMER_ID, c.CUSTOMER_NAME, SUM(s.TOTAL_AMOUNT) AS TOTAL_SPENDING FROM CUSTOMERS c
JOIN SALES s ON c.CUSTOMER_ID = s.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 1;

-- Task 12
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM PRODUCTS p
JOIN SALES s ON p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 3;

-- Task 13
SELECT c.CUSTOMER_ID, c.CUSTOMER_NAME, SUM(s.TOTAL_AMOUNT) AS TOTAL_SPENDING FROM CUSTOMERS c
JOIN SALES s ON c.CUSTOMER_ID = s.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 3;

-- Task 14 window functions 
SELECT c.CUSTOMER_ID, c.CUSTOMER_NAME, SUM(s.TOTAL_AMOUNT) AS TOTAL_SPENDING,
    RANK() OVER (
        ORDER BY SUM(s.TOTAL_AMOUNT) DESC
    ) AS CUSTOMER_RANK FROM CUSTOMERS c
JOIN SALES s ON c.CUSTOMER_ID = s.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME
ORDER BY CUSTOMER_RANK;

-- task 15
SELECT b.BRANCH_ID, b.BRANCH_NAME, SUM(s.TOTAL_AMOUNT) AS TOTAL_SALES,
    RANK() OVER (
        ORDER BY SUM(s.TOTAL_AMOUNT) DESC
    ) AS BRANCH_RANK FROM BRANCHES b
JOIN SALES s ON b.BRANCH_ID = s.BRANCH_ID
GROUP BY b.BRANCH_ID, b.BRANCH_NAME
ORDER BY BRANCH_RANK;

-- task 16
WITH PRODUCT_REVENUE AS (
    SELECT p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY, SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM PRODUCTS p
    JOIN SALES s ON p.PRODUCT_ID = s.PRODUCT_ID
    GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY
),

RANKED_PRODUCTS AS (
    SELECT PRODUCT_ID, PRODUCT_NAME, CATEGORY, TOTAL_REVENUE,
        ROW_NUMBER() OVER (
            PARTITION BY CATEGORY
            ORDER BY TOTAL_REVENUE DESC
        ) AS RN FROM PRODUCT_REVENUE
)

SELECT PRODUCT_ID, PRODUCT_NAME, CATEGORY, TOTAL_REVENUE FROM RANKED_PRODUCTS
WHERE RN = 1;

-- Task 17
SELECT SALE_ID, SALE_DATE, TOTAL_AMOUNT,
    SUM(TOTAL_AMOUNT) OVER (
        ORDER BY SALE_DATE, SALE_ID
    ) AS CUMULATIVE_SALES FROM SALES
ORDER BY SALE_DATE, SALE_ID;

-- Task 18
SELECT SALE_ID, SALE_DATE, TOTAL_AMOUNT, AVG(TOTAL_AMOUNT) OVER () AS AVERAGE_SALE_AMOUNT FROM SALES
ORDER BY SALE_ID;

-- Task 19 CTE
WITH CUSTOMER_REVENUE AS (
    SELECT c.CUSTOMER_ID, c.CUSTOMER_NAME, SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM CUSTOMERS c
    JOIN SALES s ON c.CUSTOMER_ID = s.CUSTOMER_ID
    GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME
)

SELECT * FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;
 
-- Task 20 CTE
WITH CUSTOMER_REVENUE AS (
    SELECT c.CUSTOMER_ID, c.CUSTOMER_NAME, SUM(s.TOTAL_AMOUNT) AS TOTAL_SPENDING
    FROM CUSTOMERS c
    JOIN SALES s ON c.CUSTOMER_ID = s.CUSTOMER_ID
    GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME
),

AVERAGE_SPENDING AS (
    SELECT AVG(TOTAL_SPENDING) AS AVG_SPENDING FROM CUSTOMER_REVENUE
)

SELECT cr.CUSTOMER_ID, cr.CUSTOMER_NAME, cr.TOTAL_SPENDING FROM CUSTOMER_REVENUE cr
CROSS JOIN AVERAGE_SPENDING av
WHERE cr.TOTAL_SPENDING > av.AVG_SPENDING
ORDER BY cr.TOTAL_SPENDING DESC;

-- Task 21
CREATE OR REPLACE VIEW SALES_REPORT AS
SELECT s.SALE_ID, c.CUSTOMER_NAME, p.PRODUCT_NAME, p.CATEGORY, b.BRANCH_NAME, s.QUANTITY, s.SALE_DATE, s.TOTAL_AMOUNT FROM SALES s
JOIN CUSTOMERS c ON s.CUSTOMER_ID = c.CUSTOMER_ID
JOIN PRODUCTS p ON s.PRODUCT_ID = p.PRODUCT_ID
JOIN BRANCHES b ON s.BRANCH_ID = b.BRANCH_ID;

SELECT * FROM SALES_REPORT
ORDER BY SALE_DATE;

-- Task 22
CREATE OR REPLACE MATERIALIZED VIEW TOP_CUSTOMERS AS
SELECT CUSTOMER_ID, SUM(TOTAL_AMOUNT) AS TOTAL_SPENDING FROM SALES
GROUP BY CUSTOMER_ID;

SELECT * FROM TOP_CUSTOMERS
ORDER BY TOTAL_SPENDING DESC;

SHOW VIEWS;

SHOW MATERIALIZED VIEWS;