/* TASK 1 — CREATE DATABASE AND SCHEMA */

CREATE OR REPLACE DATABASE PROJECT_8_SCD;

USE DATABASE PROJECT_8_SCD;

CREATE OR REPLACE SCHEMA CUSTOMER_HISTORY;

USE SCHEMA CUSTOMER_HISTORY;


/* TASK 2 — CREATE INITIAL CUSTOMER DIMENSION */

CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);


/* TASK 3 — CREATE FILE FORMAT AND STAGE */

CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE CUSTOMER_STAGE;

COPY INTO DIM_CUSTOMER
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_STAGE
FILE_FORMAT = CUSTOMER_CSV_FORMAT;

SELECT
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;


/* TASK 4 — DISPLAY INITIAL CUSTOMER DIMENSION */

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;


/* TASK 5 — CREATE CUSTOMER UPDATES TABLE AND STAGE */

CREATE OR REPLACE TABLE CUSTOMER_UPDATES
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);

CREATE OR REPLACE STAGE CUSTOMER_UPDATE_STAGE;

COPY INTO CUSTOMER_UPDATES
FROM @CUSTOMER_UPDATE_STAGE
FILE_FORMAT = CUSTOMER_CSV_FORMAT;

SELECT *
FROM CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;


/* TASK 6 — IDENTIFY CHANGED CUSTOMERS */

SELECT
    d.CUSTOMER_ID,
    d.CITY AS OLD_CITY,
    u.CITY AS NEW_CITY,
    d.STATE AS OLD_STATE,
    u.STATE AS NEW_STATE,
    d.MEMBERSHIP AS OLD_MEMBERSHIP,
    u.MEMBERSHIP AS NEW_MEMBERSHIP,
    d.SEGMENT AS OLD_SEGMENT,
    u.SEGMENT AS NEW_SEGMENT
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE
       d.CITY <> u.CITY
    OR d.STATE <> u.STATE
    OR d.MEMBERSHIP <> u.MEMBERSHIP
    OR d.SEGMENT <> u.SEGMENT
ORDER BY d.CUSTOMER_ID;


/* TASK 7 — IDENTIFY ATTRIBUTE-LEVEL CHANGES */

SELECT
    d.CUSTOMER_ID,
    'CITY' AS ATTRIBUTE,
    d.CITY AS OLD_VALUE,
    u.CITY AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.CITY <> u.CITY

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'STATE' AS ATTRIBUTE,
    d.STATE AS OLD_VALUE,
    u.STATE AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.STATE <> u.STATE

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'MEMBERSHIP' AS ATTRIBUTE,
    d.MEMBERSHIP AS OLD_VALUE,
    u.MEMBERSHIP AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.MEMBERSHIP <> u.MEMBERSHIP

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'SEGMENT' AS ATTRIBUTE,
    d.SEGMENT AS OLD_VALUE,
    u.SEGMENT AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.SEGMENT <> u.SEGMENT

ORDER BY CUSTOMER_ID, ATTRIBUTE;


/* TASK 8 — DEMONSTRATE THE SCD PROBLEM */

MERGE INTO DIM_CUSTOMER d
USING CUSTOMER_UPDATES u
ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHEN MATCHED THEN
    UPDATE SET
        d.CUSTOMER_NAME = u.CUSTOMER_NAME,
        d.CITY = u.CITY,
        d.STATE = u.STATE,
        d.MEMBERSHIP = u.MEMBERSHIP,
        d.SEGMENT = u.SEGMENT;


/* TASK 9 — DISPLAY UPDATED DIMENSION */

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;


/* TASK 10 — DEMONSTRATE HISTORICAL DATA LOSS */

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;


/* TASK 11 — BUSINESS IMPACT ANALYSIS */

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY AS CURRENT_CITY,
    STATE AS CURRENT_STATE,
    MEMBERSHIP AS CURRENT_MEMBERSHIP,
    SEGMENT AS CURRENT_SEGMENT
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;


/* TASK 12 — VERIFY STAGE */

LIST @CUSTOMER_STAGE;