CREATE OR REPLACE WAREHOUSE ENTERPRISE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE ENTERPRISE_WH;

CREATE OR REPLACE DATABASE ENTERPRISE_DB;

USE DATABASE ENTERPRISE_DB;

CREATE OR REPLACE SCHEMA SALES_SCHEMA;

USE SCHEMA SALES_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE SALES_STAGE
FILE_FORMAT = CSV_FORMAT;

LIST @SALES_STAGE;


CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID INT,
    CUSTOMER_NAME STRING,
    CITY STRING,
    MEMBERSHIP STRING
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID INT,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE BRANCHES (
    BRANCH_ID INT,
    BRANCH_NAME STRING,
    STATE STRING
);

CREATE OR REPLACE TABLE SALES (
    SALE_ID INT,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    BRANCH_ID INT,
    QUANTITY INT,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2)
);


COPY INTO CUSTOMERS
FROM @SALES_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO PRODUCTS
FROM @SALES_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO BRANCHES
FROM @SALES_STAGE/branches.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO SALES
FROM @SALES_STAGE/sales_history.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');


SELECT * FROM CUSTOMERS ORDER BY CUSTOMER_ID;

SELECT * FROM PRODUCTS ORDER BY PRODUCT_ID;

SELECT * FROM BRANCHES ORDER BY BRANCH_ID;

SELECT * FROM SALES ORDER BY SALE_ID;

SELECT COUNT(*) AS CUSTOMER_COUNT FROM CUSTOMERS;

SELECT COUNT(*) AS PRODUCT_COUNT FROM PRODUCTS;

SELECT COUNT(*) AS BRANCH_COUNT FROM BRANCHES;

SELECT COUNT(*) AS SALES_COUNT FROM SALES;


CREATE OR REPLACE STREAM SALES_STREAM
ON TABLE SALES;

SHOW STREAMS;

SELECT * FROM SALES_STREAM;


CREATE OR REPLACE TABLE SALES_STAGING (
    SALE_ID INT,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    BRANCH_ID INT,
    QUANTITY INT,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2)
);

COPY INTO SALES_STAGING
FROM @SALES_STAGE/new_sales.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

SELECT *
FROM SALES_STAGING
ORDER BY SALE_ID;


MERGE INTO SALES AS target
USING SALES_STAGING AS source
ON target.SALE_ID = source.SALE_ID

WHEN NOT MATCHED THEN
    INSERT (
        SALE_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        BRANCH_ID,
        QUANTITY,
        SALE_DATE,
        TOTAL_AMOUNT
    )
    VALUES (
        source.SALE_ID,
        source.CUSTOMER_ID,
        source.PRODUCT_ID,
        source.BRANCH_ID,
        source.QUANTITY,
        source.SALE_DATE,
        source.TOTAL_AMOUNT
    );


SELECT *
FROM SALES
ORDER BY SALE_ID;

SELECT *
FROM SALES_STREAM
ORDER BY SALE_ID;


SELECT SALE_ID, COUNT(*) AS COUNT
FROM SALES
GROUP BY SALE_ID
HAVING COUNT(*) > 1;


SELECT s.*
FROM SALES s
LEFT JOIN CUSTOMERS c
    ON s.CUSTOMER_ID = c.CUSTOMER_ID
WHERE c.CUSTOMER_ID IS NULL;


SELECT s.*
FROM SALES s
LEFT JOIN PRODUCTS p
    ON s.PRODUCT_ID = p.PRODUCT_ID
WHERE p.PRODUCT_ID IS NULL;


SELECT COUNT(*) AS NEWLY_INSERTED_RECORDS
FROM SALES_STAGING;

SELECT COUNT(*) AS TOTAL_SALES
FROM SALES;


SELECT *
FROM SALES
WHERE SALE_ID = 10;


DELETE FROM SALES
WHERE SALE_ID = 10;


SELECT *
FROM SALES
WHERE SALE_ID = 10;


SELECT *
FROM SALES
AT (OFFSET => -60*1)
WHERE SALE_ID = 10;


INSERT INTO SALES
SELECT *
FROM SALES
AT (OFFSET => -60*1)
WHERE SALE_ID = 10;

select * from sales;

SELECT *
FROM SALES
WHERE SALE_ID = 10;

SELECT COUNT(*) AS TOTAL_SALES
FROM SALES;


SELECT
    SALE_ID,
    METADATA$ACTION,
    METADATA$ISUPDATE
FROM SALES_STREAM
WHERE SALE_ID = 10
ORDER BY SALE_ID;

select * from sales_stream;

CREATE OR REPLACE TABLE SALES_TEST
CLONE SALES;

SELECT *
FROM SALES_TEST
ORDER BY SALE_ID;

INSERT INTO SALES_TEST (
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    QUANTITY,
    SALE_DATE,
    TOTAL_AMOUNT
)
VALUES (
    11,
    1,
    101,
    1,
    1,
    '2026-07-11',
    60000
);

SELECT *
FROM SALES_TEST
ORDER BY SALE_ID;

SELECT *
FROM SALES
ORDER BY SALE_ID;

SELECT COUNT(*) AS SALES_COUNT
FROM SALES;

SELECT COUNT(*) AS SALES_TEST_COUNT
FROM SALES_TEST;

CREATE OR REPLACE TASK DAILY_SALES_LOAD
WAREHOUSE = ENTERPRISE_WH
SCHEDULE = 'USING CRON 0 0 * * * UTC'
AS
MERGE INTO SALES AS target
USING SALES_STAGING AS source
ON target.SALE_ID = source.SALE_ID

WHEN NOT MATCHED THEN
    INSERT (
        SALE_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        BRANCH_ID,
        QUANTITY,
        SALE_DATE,
        TOTAL_AMOUNT
    )
    VALUES (
        source.SALE_ID,
        source.CUSTOMER_ID,
        source.PRODUCT_ID,
        source.BRANCH_ID,
        source.QUANTITY,
        source.SALE_DATE,
        source.TOTAL_AMOUNT
    );

ALTER TASK DAILY_SALES_LOAD RESUME;

SHOW TASKS;

SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'DAILY_SALES_LOAD'
ORDER BY SCHEDULED_TIME DESC;

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMERS c
JOIN SALES s
    ON c.CUSTOMER_ID = s.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;


SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES b
JOIN SALES s
    ON b.BRANCH_ID = s.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS p
JOIN SALES s
    ON p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    DATE_TRUNC('MONTH', SALE_DATE) AS MONTH,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES
GROUP BY DATE_TRUNC('MONTH', SALE_DATE)
ORDER BY MONTH;

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMERS c
JOIN SALES s
    ON c.CUSTOMER_ID = s.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES b
JOIN SALES s
    ON b.BRANCH_ID = s.BRANCH_ID
GROUP BY
    b.BRANCH_ID,
    b.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS p
JOIN SALES s
    ON p.PRODUCT_ID = s.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    COUNT(s.SALE_ID) AS PURCHASE_COUNT
FROM CUSTOMERS c
JOIN SALES s
    ON c.CUSTOMER_ID = s.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY PURCHASE_COUNT DESC;

SELECT
    SALE_ID,
    SALE_DATE,
    TOTAL_AMOUNT,
    SUM(TOTAL_AMOUNT) OVER (
        ORDER BY SALE_DATE, SALE_ID
    ) AS RUNNING_REVENUE
FROM SALES
ORDER BY SALE_DATE, SALE_ID;

SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    RANK() OVER (
        ORDER BY SUM(s.TOTAL_AMOUNT) DESC
    ) AS CUSTOMER_RANK
FROM CUSTOMERS c
JOIN SALES s
    ON c.CUSTOMER_ID = s.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME
ORDER BY CUSTOMER_RANK;

CREATE OR REPLACE VIEW CUSTOMER_REVENUE AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    SUM(s.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMERS c
JOIN SALES s
    ON c.CUSTOMER_ID = s.CUSTOMER_ID
GROUP BY
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME;

SELECT *
FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;

CREATE OR REPLACE MATERIALIZED VIEW BRANCH_REVENUE AS
SELECT
    BRANCH_ID,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES
GROUP BY BRANCH_ID;

SELECT *
FROM BRANCH_REVENUE
ORDER BY TOTAL_REVENUE DESC;

SELECT
    b.BRANCH_ID,
    b.BRANCH_NAME,
    r.TOTAL_REVENUE
FROM BRANCHES b
JOIN BRANCH_REVENUE r
    ON b.BRANCH_ID = r.BRANCH_ID
ORDER BY r.TOTAL_REVENUE DESC;

SELECT *
FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;

SELECT *
FROM BRANCH_REVENUE
ORDER BY TOTAL_REVENUE DESC;