CREATE WAREHOUSE CUSTOMER_HISTORY_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
USE WAREHOUSE CUSTOMER_HISTORY_WH;

CREATE DATABASE CUSTOMER_HISTORY_DB;
USE DATABASE CUSTOMER_HISTORY_DB;

CREATE SCHEMA CUSTOMER_SCHEMA;
USE SCHEMA CUSTOMER_SCHEMA;

SELECT
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE CUSTOMER_STAGE
FILE_FORMAT = CSV_FORMAT;



-- Phase 2
CREATE OR REPLACE TABLE DIM_CUSTOMER_SCD1 (
    CUSTOMER_KEY INT AUTOINCREMENT,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

DESC TABLE DIM_CUSTOMER_SCD1;

COPY INTO DIM_CUSTOMER_SCD1
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_STAGE/customers_initial.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

SELECT * FROM DIM_CUSTOMER_SCD1
ORDER BY CUSTOMER_ID;

SELECT COUNT(*) AS TYPE1_RECORD_COUNT
FROM DIM_CUSTOMER_SCD1;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);

COPY INTO CUSTOMER_UPDATES
FROM @CUSTOMER_STAGE/customer_updates.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

SELECT * FROM CUSTOMER_UPDATES
ORDER BY CUSTOMER_ID;

UPDATE DIM_CUSTOMER_SCD1 t
SET
    CUSTOMER_NAME = u.CUSTOMER_NAME,
    CITY = u.CITY,
    STATE = u.STATE,
    MEMBERSHIP = u.MEMBERSHIP,
    SEGMENT = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE t.CUSTOMER_ID = u.CUSTOMER_ID;

SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT FROM DIM_CUSTOMER_SCD1
ORDER BY CUSTOMER_ID;

SELECT COUNT(*) AS TYPE1_RECORD_COUNT FROM DIM_CUSTOMER_SCD1;

SELECT CUSTOMER_ID, CITY, STATE, MEMBERSHIP FROM DIM_CUSTOMER_SCD1
WHERE CUSTOMER_ID = 101;

CREATE OR REPLACE TABLE DIM_CUSTOMER_SCD2 (
    CUSTOMER_KEY INT AUTOINCREMENT,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

DESC TABLE DIM_CUSTOMER_SCD2;

CREATE OR REPLACE TABLE CUSTOMER_INITIAL (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

COPY INTO CUSTOMER_INITIAL
FROM @CUSTOMER_STAGE/customers_initial.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

INSERT INTO DIM_CUSTOMER_SCD2 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    '2026-01-01'::DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_INITIAL;

SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT FROM DIM_CUSTOMER_SCD2
ORDER BY CUSTOMER_ID;

SELECT COUNT(*) AS TOTAL_RECORDS FROM DIM_CUSTOMER_SCD2;

SELECT COUNT(*) AS CURRENT_RECORDS FROM DIM_CUSTOMER_SCD2
WHERE IS_CURRENT = TRUE;

UPDATE DIM_CUSTOMER_SCD2
SET
    EXPIRY_DATE = '2026-03-31',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101
  AND IS_CURRENT = TRUE;

  INSERT INTO DIM_CUSTOMER_SCD2 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_UPDATES
WHERE CUSTOMER_ID = 101;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORDS,
    COUNT_IF(IS_CURRENT = FALSE) AS HISTORICAL_RECORDS
FROM DIM_CUSTOMER_SCD2;

UPDATE DIM_CUSTOMER_SCD2
SET
    EXPIRY_DATE = '2026-04-04',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_SCD2 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_UPDATES
WHERE CUSTOMER_ID = 103;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 103
ORDER BY EFFECTIVE_DATE;

SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORDS,
    COUNT_IF(IS_CURRENT = FALSE) AS HISTORICAL_RECORDS
FROM DIM_CUSTOMER_SCD2;

UPDATE DIM_CUSTOMER_SCD2
SET
    EXPIRY_DATE = '2026-04-09',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_SCD2 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_UPDATES
WHERE CUSTOMER_ID = 104;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 104
ORDER BY EFFECTIVE_DATE;

SELECT
    COUNT(*) AS TOTAL_RECORDS,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORDS,
    COUNT_IF(IS_CURRENT = FALSE) AS HISTORICAL_RECORDS
FROM DIM_CUSTOMER_SCD2;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_SCD2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_SCD2
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MEMBERSHIP,
    CITY,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 101  AND '2026-03-15'::DATE BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

SELECT
    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_SCD1) AS SCD1_RECORD_COUNT,

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_SCD2) AS SCD2_RECORD_COUNT,4

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_SCD2
     WHERE IS_CURRENT = TRUE) AS SCD2_CURRENT_COUNT,

    (SELECT COUNT(*)
     FROM DIM_CUSTOMER_SCD2
     WHERE IS_CURRENT = FALSE) AS SCD2_HISTORICAL_COUNT;

    
  