/* TASK 1 — CREATE DATABASE AND SCHEMA */

CREATE OR REPLACE DATABASE PROJECT_11_SCD;

USE DATABASE PROJECT_11_SCD;

CREATE OR REPLACE SCHEMA CUSTOMER_HISTORY;

USE SCHEMA CUSTOMER_HISTORY;


/* TASK 2 — CREATE HYBRID DIMENSION TABLE */

CREATE OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    PREVIOUS_CITY VARCHAR(100),
    STATE VARCHAR(100),
    CURRENT_MEMBERSHIP VARCHAR(50),
    PREVIOUS_MEMBERSHIP VARCHAR(50),
    HISTORICAL_MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);


/* TASK 3 — LOAD INITIAL DIMENSION DATA */

CREATE OR REPLACE FILE FORMAT CUSTOMER_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE CUSTOMER_STAGE;

COPY INTO DIM_CUSTOMER
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    SEGMENT
)
FROM @CUSTOMER_STAGE
FILE_FORMAT = CUSTOMER_CSV_FORMAT
MATCH_BY_COLUMN_NAME = NONE;

UPDATE DIM_CUSTOMER
SET
    PREVIOUS_CITY = NULL,
    PREVIOUS_MEMBERSHIP = NULL,
    HISTORICAL_MEMBERSHIP = CURRENT_MEMBERSHIP,
    EFFECTIVE_DATE = '2026-01-01',
    EXPIRY_DATE = '9999-12-31',
    IS_CURRENT = TRUE;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;


/* TASK 4 — DISPLAY INITIAL DIMENSION STATE */

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;


/* TASK 5 — APPLY HYBRID UPDATES */


/* Create update table */

CREATE OR REPLACE TABLE CUSTOMER_UPDATES
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50),
    EFFECTIVE_DATE DATE
);


/* Create update stage */

CREATE OR REPLACE STAGE CUSTOMER_UPDATE_STAGE;


/* Load customer_updates.csv */

COPY INTO CUSTOMER_UPDATES
FROM @CUSTOMER_UPDATE_STAGE
FILE_FORMAT = CUSTOMER_CSV_FORMAT;


/* Step 1 — Expire active versions */

UPDATE DIM_CUSTOMER d
SET
    EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE;


/* Step 2 — Insert new active versions */

INSERT INTO DIM_CUSTOMER
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    u.CUSTOMER_ID,
    u.CUSTOMER_NAME,

    u.CITY AS CITY,

    CASE
        WHEN d.CITY <> u.CITY THEN d.CITY
        ELSE NULL
    END AS PREVIOUS_CITY,

    u.STATE AS STATE,

    u.MEMBERSHIP AS CURRENT_MEMBERSHIP,

    d.CURRENT_MEMBERSHIP AS PREVIOUS_MEMBERSHIP,

    u.MEMBERSHIP AS HISTORICAL_MEMBERSHIP,

    u.SEGMENT AS SEGMENT,

    u.EFFECTIVE_DATE,

    '9999-12-31'::DATE,

    TRUE

FROM DIM_CUSTOMER d

JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID

WHERE d.EXPIRY_DATE = DATEADD(DAY, -1, u.EFFECTIVE_DATE);


/* Step 3 — Synchronize current and prior attributes */

UPDATE DIM_CUSTOMER d
SET
    CITY = u.CITY,

    PREVIOUS_CITY =
        CASE
            WHEN old.CITY <> u.CITY THEN old.CITY
            ELSE NULL
        END,

    STATE = u.STATE,

    CURRENT_MEMBERSHIP = u.MEMBERSHIP,

    PREVIOUS_MEMBERSHIP = old.CURRENT_MEMBERSHIP

FROM CUSTOMER_UPDATES u

JOIN DIM_CUSTOMER old
    ON old.CUSTOMER_ID = u.CUSTOMER_ID

WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;


/* Restore the correct historical membership for each row version */

UPDATE DIM_CUSTOMER d
SET
    HISTORICAL_MEMBERSHIP =
        CASE
            WHEN d.IS_CURRENT = TRUE
                THEN u.MEMBERSHIP
            ELSE d.HISTORICAL_MEMBERSHIP
        END
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;


/* Display complete history */

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;


/* TASK 6 — DISPLAY COMPLETE DIMENSION HISTORY */

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;


/* TASK 7 — DISPLAY ACTIVE CUSTOMER REPORT */

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;


/* TASK 8 — POINT-IN-TIME HISTORICAL QUERY */

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101
  AND '2026-03-15'::DATE
      BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;


/* TASK 9 — METRIC VALIDATION AND RECORD COUNTS */

SELECT
    'TOTAL RECORD COUNT' AS METRIC,
    COUNT(*) AS VALUE
FROM DIM_CUSTOMER

UNION ALL

SELECT
    'CURRENT RECORD COUNT' AS METRIC,
    COUNT(*) AS VALUE
FROM DIM_CUSTOMER
WHERE IS_CURRENT = TRUE

UNION ALL

SELECT
    'HISTORICAL RECORD COUNT' AS METRIC,
    COUNT(*) AS VALUE
FROM DIM_CUSTOMER
WHERE IS_CURRENT = FALSE;