CREATE WAREHOUSE RETAIL_SNOWFLAKE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
USE WAREHOUSE RETAIL_SNOWFLAKE_WH;

CREATE DATABASE RETAIL_SNOWFLAKE_DB;
USE DATABASE RETAIL_SNOWFLAKE_DB;

CREATE SCHEMA SALES_SCHEMA;
USE SCHEMA SALES_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE OR REPLACE STAGE RETAIL_SNOWFLAKE_STAGE
FILE_FORMAT = CSV_FORMAT;

SELECT
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();

SHOW STAGES;

CREATE OR REPLACE TABLE DIM_REGION (
    REGION_ID INT PRIMARY KEY,
    REGION_NAME VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_STATE (
    STATE_ID INT PRIMARY KEY,
    STATE_NAME VARCHAR(100),
    REGION_ID INT
);

CREATE OR REPLACE TABLE DIM_CITY (
    CITY_ID INT PRIMARY KEY,
    CITY_NAME VARCHAR(100),
    STATE_ID INT
);

CREATE OR REPLACE TABLE DIM_CATEGORY (
    CATEGORY_ID INT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_BRAND (
    BRAND_ID INT PRIMARY KEY,
    BRAND_NAME VARCHAR(100),
    CATEGORY_ID INT
);

CREATE OR REPLACE TABLE DIM_YEAR (
    YEAR_ID INT PRIMARY KEY,
    YEAR_VALUE INT
);

CREATE OR REPLACE TABLE DIM_QUARTER (
    QUARTER_ID INT PRIMARY KEY,
    QUARTER_NAME VARCHAR(10),
    YEAR_ID INT
);

CREATE OR REPLACE TABLE DIM_MONTH (
    MONTH_ID INT PRIMARY KEY,
    MONTH_NAME VARCHAR(20),
    QUARTER_ID INT
);

SHOW TABLES;

INSERT INTO DIM_REGION (REGION_ID, REGION_NAME)
VALUES
(1, 'South'),
(2, 'West'),
(3, 'North'),
(4, 'East');

SELECT * FROM DIM_REGION
ORDER BY REGION_ID;

INSERT INTO DIM_STATE (STATE_ID, STATE_NAME, REGION_ID)
VALUES
(1, 'Telangana', 1),
(2, 'Karnataka', 1),
(3, 'Tamil Nadu', 1),
(4, 'Maharashtra', 2),
(5, 'Delhi', 3),
(6, 'Gujarat', 2),
(7, 'West Bengal', 4),
(8, 'Rajasthan', 3),
(9, 'Kerala', 1),
(10, 'Uttar Pradesh', 3);

SELECT s.STATE_ID, s.STATE_NAME, r.REGION_NAME FROM DIM_STATE s
JOIN DIM_REGION r ON s.REGION_ID = r.REGION_ID
ORDER BY s.STATE_ID;

INSERT INTO DIM_CITY (CITY_ID, CITY_NAME, STATE_ID)
VALUES
(1, 'Hyderabad', 1),
(2, 'Bangalore', 2),
(3, 'Chennai', 3),
(4, 'Mumbai', 4),
(5, 'Delhi', 5),
(6, 'Ahmedabad', 6),
(7, 'Kolkata', 7),
(8, 'Jaipur', 8),
(9, 'Kochi', 9),
(10, 'Lucknow', 10);

SELECT c.CITY_NAME, s.STATE_NAME, r.REGION_NAME FROM DIM_CITY c
JOIN DIM_STATE s ON c.STATE_ID = s.STATE_ID
JOIN DIM_REGION r ON s.REGION_ID = r.REGION_ID
ORDER BY c.CITY_ID;

INSERT INTO DIM_CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES
(1, 'Electronics'),
(2, 'Accessories'),
(3, 'Office Equipment'),
(4, 'Networking'),
(5, 'Storage'),
(6, 'Mobile Accessories');

INSERT INTO DIM_BRAND (BRAND_ID, BRAND_NAME, CATEGORY_ID)
VALUES
(1, 'Dell', 1),
(2, 'Samsung', 1),
(3, 'Apple', 1),
(4, 'LG', 1),
(5, 'Logitech', 2),
(6, 'HP', 2),
(7, 'Sony', 2),
(8, 'JBL', 2),
(9, 'Canon', 3),
(10, 'Epson', 3),
(11, 'TP-Link', 4),
(12, 'Cisco', 4),
(13, 'Seagate', 5),
(14, 'SanDisk', 5),
(15, 'Mi', 6),
(16, 'Anker', 6);

SELECT b.BRAND_NAME, c.CATEGORY_NAME
FROM DIM_BRAND b
JOIN DIM_CATEGORY c ON b.CATEGORY_ID = c.CATEGORY_ID
ORDER BY c.CATEGORY_NAME, b.BRAND_NAME;

INSERT INTO DIM_YEAR (YEAR_ID, YEAR_VALUE)
VALUES
(1, 2026);

INSERT INTO DIM_QUARTER (QUARTER_ID, QUARTER_NAME, YEAR_ID)
VALUES
(1, 'Q3', 1);

INSERT INTO DIM_MONTH (MONTH_ID, MONTH_NAME, QUARTER_ID)
VALUES
(7, 'July', 1);

SELECT y.YEAR_VALUE, q.QUARTER_NAME, m.MONTH_NAME FROM DIM_MONTH m
JOIN DIM_QUARTER q ON m.QUARTER_ID = q.QUARTER_ID
JOIN DIM_YEAR y ON q.YEAR_ID = y.YEAR_ID;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    BRAND VARCHAR(100),
    PRICE NUMBER(12,2)
);

CREATE OR REPLACE TABLE DIM_BRANCH (
    BRANCH_ID INT PRIMARY KEY,
    BRANCH_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    REGION VARCHAR(50),
    MANAGER_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID INT PRIMARY KEY,
    DATE DATE,
    DAY INT,
    DAY_NAME VARCHAR(20),
    WEEK_NO INT,
    MONTH VARCHAR(20),
    QUARTER VARCHAR(10),
    YEAR INT,
    IS_WEEKEND VARCHAR(5)
);

COPY INTO DIM_CUSTOMER
FROM @RETAIL_SNOWFLAKE_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO DIM_PRODUCT
FROM @RETAIL_SNOWFLAKE_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO DIM_BRANCH
FROM @RETAIL_SNOWFLAKE_STAGE/branches.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

COPY INTO DIM_DATE
FROM @RETAIL_SNOWFLAKE_STAGE/calendar.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

SELECT COUNT(*) FROM DIM_CUSTOMER;

SELECT COUNT(*) FROM DIM_PRODUCT;

SELECT COUNT(*) FROM DIM_BRANCH;

SELECT COUNT(*) FROM DIM_DATE;

ALTER TABLE DIM_CUSTOMER
ADD COLUMN CITY_ID INT;

TRUNCATE TABLE DIM_CITY;

INSERT INTO DIM_CITY (CITY_ID, CITY_NAME, STATE_ID)
VALUES
(1, 'Ahmedabad', 6),
(2, 'Bangalore', 2),
(3, 'Bhopal', 3),
(4, 'Chandigarh', 3),
(5, 'Chennai', 3),
(6, 'Coimbatore', 3),
(7, 'Delhi', 5),
(8, 'Hyderabad', 1),
(9, 'Jaipur', 8),
(10, 'Kochi', 9),
(11, 'Kolkata', 7),
(12, 'Lucknow', 10),
(13, 'Mumbai', 4),
(14, 'Mysore', 2),
(15, 'Nagpur', 4),
(16, 'Patna', 3),
(17, 'Thiruvananthapuram', 9),
(18, 'Vijayawada', 1),
(19, 'Visakhapatnam', 1),
(20, 'Warangal', 1);

SELECT * FROM DIM_CITY
ORDER BY CITY_ID;

UPDATE DIM_CUSTOMER c
SET CITY_ID = d.CITY_ID
FROM DIM_CITY d
WHERE c.CITY = d.CITY_NAME;

SELECT COUNT(*) AS MISSING_CITY_ID FROM DIM_CUSTOMER
WHERE CITY_ID IS NULL;

UPDATE DIM_BRANCH b
SET CITY_ID = c.CITY_ID
FROM DIM_CITY c
WHERE b.CITY = c.CITY_NAME;

SELECT BRANCH_ID, BRANCH_NAME, CITY, CITY_ID FROM DIM_BRANCH
ORDER BY BRANCH_ID;

SELECT COUNT(*) AS MISSING_CITY_ID FROM DIM_BRANCH
WHERE CITY_ID IS NULL;

ALTER TABLE DIM_PRODUCT
ADD COLUMN BRAND_ID INT;

UPDATE DIM_PRODUCT p
SET BRAND_ID = b.BRAND_ID
FROM DIM_BRAND b
WHERE p.BRAND = b.BRAND_NAME;

SELECT p.PRODUCT_ID, p.PRODUCT_NAME, p.BRAND, p.CATEGORY, p.BRAND_ID FROM DIM_PRODUCT p
ORDER BY p.PRODUCT_ID;

SELECT COUNT(*) AS MISSING_BRAND_ID FROM DIM_PRODUCT
WHERE BRAND_ID IS NULL;

SELECT p.PRODUCT_NAME, b.BRAND_NAME, c.CATEGORY_NAME FROM DIM_PRODUCT p
JOIN DIM_BRAND b ON p.BRAND_ID = b.BRAND_ID
JOIN DIM_CATEGORY c ON b.CATEGORY_ID = c.CATEGORY_ID
ORDER BY p.PRODUCT_ID;

DESC TABLE DIM_DATE;

ALTER TABLE DIM_DATE
ADD COLUMN MONTH_ID INT;

UPDATE DIM_DATE d
SET MONTH_ID = m.MONTH_ID
FROM DIM_MONTH m
WHERE d.MONTH = m.MONTH_NAME;

SELECT COUNT(*) AS MISSING_MONTH_ID FROM DIM_DATE
WHERE MONTH_ID IS NULL;

SELECT d.DATE, d.MONTH, m.MONTH_NAME, q.QUARTER_NAME, y.YEAR_VALUE FROM DIM_DATE d
JOIN DIM_MONTH m ON d.MONTH_ID = m.MONTH_ID
JOIN DIM_QUARTER q ON m.QUARTER_ID = q.QUARTER_ID
JOIN DIM_YEAR y ON q.YEAR_ID = y.YEAR_ID
ORDER BY d.DATE;

SELECT c.CUSTOMER_ID, c.CUSTOMER_NAME, city.CITY_NAME, s.STATE_NAME, r.REGION_NAME FROM DIM_CUSTOMER c
JOIN DIM_CITY city ON c.CITY_ID = city.CITY_ID
JOIN DIM_STATE s ON city.STATE_ID = s.STATE_ID
JOIN DIM_REGION r ON s.REGION_ID = r.REGION_ID
ORDER BY c.CUSTOMER_ID;

SELECT b.BRANCH_ID, b.BRANCH_NAME, city.CITY_NAME, s.STATE_NAME, r.REGION_NAME FROM DIM_BRANCH b
JOIN DIM_CITY city ON b.CITY_ID = city.CITY_ID
JOIN DIM_STATE s ON city.STATE_ID = s.STATE_ID
JOIN DIM_REGION r ON s.REGION_ID = r.REGION_ID
ORDER BY b.BRANCH_ID;

SELECT d.DATE_ID, d.DATE, m.MONTH_NAME, q.QUARTER_NAME, y.YEAR_VALUE FROM DIM_DATE d
JOIN DIM_MONTH m ON d.MONTH_ID = m.MONTH_ID
JOIN DIM_QUARTER q ON m.QUARTER_ID = q.QUARTER_ID
JOIN DIM_YEAR y ON q.YEAR_ID = y.YEAR_ID
ORDER BY d.DATE_ID;

CREATE OR REPLACE TABLE FACT_SALES (
    SALE_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    BRANCH_ID INT,
    DATE_ID INT,
    QUANTITY INT,
    TOTAL_AMOUNT NUMBER(12,2)
);

COPY INTO FACT_SALES
FROM @RETAIL_SNOWFLAKE_STAGE/sales.csv
FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');

SELECT COUNT(*) AS TOTAL_SALES FROM FACT_SALES;

SELECT r.REGION_NAME, SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_BRANCH b ON f.BRANCH_ID = b.BRANCH_ID
JOIN DIM_CITY city ON b.CITY_ID = city.CITY_ID
JOIN DIM_STATE s ON city.STATE_ID = s.STATE_ID
JOIN DIM_REGION r ON s.REGION_ID = r.REGION_ID
GROUP BY r.REGION_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT c.CATEGORY_NAME, SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
JOIN DIM_BRAND b ON p.BRAND_ID = b.BRAND_ID
JOIN DIM_CATEGORY c ON b.CATEGORY_ID = c.CATEGORY_ID
GROUP BY c.CATEGORY_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT y.YEAR_VALUE, q.QUARTER_NAME, m.MONTH_NAME, SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES f
JOIN DIM_DATE d ON f.DATE_ID = d.DATE_ID
JOIN DIM_MONTH m ON d.MONTH_ID = m.MONTH_ID
JOIN DIM_QUARTER q ON m.QUARTER_ID = q.QUARTER_ID
JOIN DIM_YEAR y ON q.YEAR_ID = y.YEAR_ID
GROUP BY y.YEAR_VALUE, q.QUARTER_NAME, m.MONTH_NAME;

SELECT r.REGION_NAME, SUM(f.TOTAL_AMOUNT)
FROM FACT_SALES f
JOIN DIM_BRANCH b ON f.BRANCH_ID = b.BRANCH_ID
JOIN DIM_CITY c ON b.CITY_ID = c.CITY_ID
JOIN DIM_STATE s ON c.STATE_ID = s.STATE_ID
JOIN DIM_REGION r ON s.REGION_ID = r.REGION_ID
GROUP BY r.REGION_NAME;


